name: Sync PR with Issue

on:
  pull_request:
    types: [opened]

jobs:
  sync-pr-info:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Extract branch info
      id: extract
      run: echo "::set-output name=issue_number::$(echo '${{ github.head_ref }}' | grep -oP '(?<=-)\d+')"

    - name: Get Issue Details
      id: issue
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/issues/${{ steps.extract.outputs.issue_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Update PR
      run: |
        ISSUE_TITLE=$(echo '${{ steps.issue.outputs.data }}' | jq -r '.title')
        if [ -z "$ISSUE_TITLE" ]; then
          echo "Failed to fetch the issue title."
          exit 1
        fi
    
        ASSIGNEES=$(echo "${{ steps.issue.outputs.data }}" | jq -r "[.assignees[].login] | join(',')")
        LABELS=$(echo "${{ steps.issue.outputs.data }}" | jq -r "[.labels[].name] | join(',')")
    
        # Update PR Title
        if [[ ! -z "$ISSUE_TITLE" ]]; then
          gh pr edit ${{ github.event.pull_request.number }} --title "$ISSUE_TITLE"
        fi
    
        # Update PR Body
        PR_BODY="Closes #${{ steps.extract.outputs.issue_number }}"
        gh pr edit ${{ github.event.pull_request.number }} --body "$PR_BODY"
        )

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
