   name: Create Pull Request

   on:
     push:
       branches:
         - 'feat-*'

   jobs:
     create-pr:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v4
           with:
             token: ${{ secrets.TOKEN }}
             branch: master
             commit-message: Automated PR for Issue ${{ github.event.issue.number }}
             title: Automated PR from Issue #${{ github.event.inputs.issue_number }}
             labels: ${{ github.event.inputs.issue_labels }}
             assignees: ${{ github.event.inputs.issue_assignees }}
